services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app:cached
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app:cached
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_BACKEND_URL=http://backend:8000
    command: npm run dev
